spring:
  main:
    banner-mode: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/history
weather:
  current: http://api.weatherapi.com/v1/current.json?key=${WEATHER_KEY}
  forecast: http://api.weatherapi.com/v1/forecast.json?key=${WEATHER_KEY}
mapData:
  url:

